CREATE TABLE telemetry (
    date_entry                      date,
    time_step                       time,
    tire_temps                      float[4][1][1],
    tire_pressures                  float[4],
    velocity                        NUMERIC(12, 6),
    location                        NUMERIC(12, 6)[2],
    accelerator_input               NUMERIC(12, 8),
    brake_input                     NUMERIC(12, 8),
    steering_angle                  NUMERIC(12, 6),
    gyro_pitch                      NUMERIC(12, 6),
    gyro_yaw                        NUMERIC(12, 6),
    gyro_roll                       NUMERIC(12, 6),
    x_acceleration                  NUMERIC(12, 6),
    y_acceleration                  NUMERIC(12, 6),
    z_acceleration                  NUMERIC(12, 6),
    total_power_draw                float,
    active_suspension_power_draw    float[4],
    motor_power_draw                float[2],
    battery_voltage                 float,
    traction_loss                   float,
    abs_throttle_limiting           float[2],
    limited_slip_usage              float[2],
    log                             varchar[100]
);